Add CPU Core Count patch to ProvideCurrentCpuInfo
acidanthera/OpenCorePkg pull request #277
Opened 2021-07-13 19:48 UTC by Shaneee

2021-07-15 20:31 UTC, Amachik approved these changes

2021-07-22 09:22 UTC, mhaeuser commented
I understand that you simply replicated our patch structure with your patch, but this is unreviewable for me. Our patch definitions are sparse on information as well, but it's a different thing whether the maintainer or an external contributor adds such code. We understand our own patches because we wrote them, but if you want to merge yours, it needs to be maintained. This means either you'd need to step up and maintain the patch yourself at our pace (this would need team discussion first, this is just a floating variant), or you need to provide enough information that we can do so ourselves easily. For example, I don't want to throw the kernel into IDA to figure out what this even does.

By that I don't mean that it will be fine if you provide more information, merely I need the information to think about it. I would guess this is simply a hack to substitute dynamic core count retrieval for AMD with a "hardcoded" (with the dynamically retrieved value by OC) constant, but that is not written down anywhere. If you can provide some reason for non-AMD CPUs why this is helpful, that'd make the merge much more likely to happen. If you can show that you can make good use of the patch engine for AMD, maybe we could rather discuss exposing it to drivers rather than merging AMD patches. But that'd require an overview of all patches with their rationales and implementations.

2021-07-22 09:30 UTC, mhaeuser requested changes
See previous comment for missing explanations.

2021-07-22 09:30 UTC, mhaeuser commented on Library/OcAppleKernelLib/CpuidPatches.c
> +      );
I would just use WriteUnaligned32, that should be the fastest on x86.

2021-07-22 09:30 UTC, mhaeuser commented on Library/OcAppleKernelLib/CpuidPatches.c
> +    CoreCount = (UINT16) (CpuInfo->CoreCount);
Superfluous cast

2021-07-22 09:30 UTC, mhaeuser commented on Library/OcAppleKernelLib/CpuidPatches.c
> +  if (OcMatchDarwinVersion (KernelVersion, KERNEL_VERSION_CATALINA_MIN, 0)) {
Indentation

2021-07-22 09:30 UTC, mhaeuser commented on Library/OcAppleKernelLib/CpuidPatches.c
> +    CopyMem ( &mProvideCurrentCpuInfoCoreCountReplace,
New-line before argument

2021-07-22 09:30 UTC, mhaeuser commented on Library/OcAppleKernelLib/CpuidPatches.c
> +    CopyMem ( &mProvideCurrentCpuInfoCoreCountReplace,
New-line before argument

2021-07-22 09:30 UTC, mhaeuser commented on Library/OcAppleKernelLib/CpuidPatches.c
> +// Offset of value in below patch.
For proper Doxgen comment emission, please use
```
///
/// Offset of value in below patch.
///
```
Also please try to be clearer, this refers to the offset of the CoreCount argument within the instruction.

2021-07-22 16:33 UTC, Shaneee commented
Thank you for the review. We will take this under consideration, we have another approach for this in the works. We will apply your recommendations to this and submit when we are ready.

2021-07-22 16:33 UTC, closed without merging

2023-02-06 21:35 UTC, dreamwhite commented
Any update on this? @Shaneee